version: '3'
services:
  postgres_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  rails:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    ports:
      - 3000:3000

